In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import re
import seaborn as sns
import sys, os
import pathlib
from pathlib import Path
from pydantic import ValidationError
from olist_churn_prediction.paths import SRC_DIR, PROCESSED_DIR, INTERIM_DIR
from olist_churn_prediction.schemas_interim import MergedDfSchemaInterim

In [4]:
#df = pd.read_parquet(INTERIM_DIR / "merged_df.parquet")

In [2]:
df = pd.read_parquet(INTERIM_DIR / "merged_df.parquet")

for i, row in df.head(5).iterrows():
    try:
        MergedDfSchemaInterim.model_validate(row.to_dict())
    except ValidationError as e:
        print(f"\nRow {i}:\n{e}\n")

In [3]:
display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97578 entries, 0 to 97577
Data columns (total 33 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       97578 non-null  string
 1   order_products_value           97578 non-null  float32
 2   order_freight_value            97578 non-null  float32
 3   order_items_qty                97578 non-null  Int64
 4   order_purchase_timestamp       97578 non-null  datetime64[ns]
 5   order_aproved_at               97578 non-null  datetime64[ns]
 6   order_estimated_delivery_date  97578 non-null  datetime64[ns]
 7   order_delivered_customer_date  97578 non-null  datetime64[ns]
 8   customer_id                    97578 non-null  string
 9   customer_city                  97578 non-null  string
 10  customer_state                 97578 non-null  string
 11  customer_zip_code_prefix       97578 non-null  string
 12  product_name_lenght            97578 non-null  Int64
 13  product_description_lenght     97578 non-null  Int64
 14  product_photos_qty             97578 non-null  Int64
 15  product_id                     97578 non-null  string
 16  review_id                      97578 non-null  string
 17  review_score                   97578 non-null  Int64
 18  review_creation_date           97578 non-null  datetime64[ns]
 19  review_answer_timestamp        97578 non-null  datetime64[ns, UTC]
 20  product_category_name_english  97578 non-null  object
 21  value                          88563 non-null  float32
 22  installments                   88563 non-null  Int64
 23  sequential                     88563 non-null  Int64
 24  product_weight_g               97560 non-null  float32
 25  product_length_cm              97560 non-null  float32
 26  product_height_cm              97560 non-null  float32
 27  product_width_cm               97560 non-null  float32
 28  customer_unique_id             97578 non-null  string
 29  seller_id                      97561 non-null  string
 30  seller_zip_code_prefix         97561 non-null  string
 31  seller_city                    97561 non-null  string
 32  seller_state                   97561 non-null  string
dtypes: Int64(7), datetime64[ns, UTC](1), datetime64[ns](5), float32(7), object(1), string(12)
memory usage: 22.6+ MB

None

In [7]:
display(df.head())

,order_id,order_products_value,order_freight_value,order_items_qty,order_purchase_timestamp,order_aproved_at,order_estimated_delivery_date,order_delivered_customer_date,customer_id,customer_city,...,sequential,product_weight_g,product_length_cm,product_height_cm,product_width_cm,customer_unique_id,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,b95df3cef5297e79ef709ba256518f6f,349.899994,13.840000,1,2017-01-31 17:19:01,2017-02-01 02:41:21.549551,2017-03-15,2017-02-06 11:04:24.154259,297dcf281305aabfee256d313076af2b,guaratuba,...,1,900.0,25.0,12.0,38.0,a27e24da3a7dc34713304a30896a3c4e,ccc4bbb5f32a6ab2b7066a4130f114e3,803,curitiba,pr
1,59af46052a799e80e2f0c665c587731d,15.000000,15.100000,1,2017-09-09 19:52:54,2017-09-10 20:03:31.535281,2017-10-02,2017-09-13 20:17:41.296915,b7563d94162ed0aa3f8d9cada4bcc536,uberlandia,...,1,250.0,30.0,20.0,32.0,83c5f96adba9983897eb09729577aa6b,ce27a3cc3c8cc1ea79d11e561e9bebb6,030,sao_paulo,sp
2,a3e6136894621db402a772c6bc72a12a,238.899994,18.000000,1,2017-01-30 17:00:09,2017-01-30 17:31:25.438253,2017-03-07,2017-02-06 15:43:04.758566,f102cb15ec41ca30fa2902da06495f6b,itapevi,...,1,7950.0,61.0,13.0,61.0,de5a83eec57b3ac456dca340651c030a,8581055ce74af1daba164fdbd55a40de,071,guarulhos,sp
3,b675ea5a618922f6e679e30531b8957b,29.990000,18.230000,1,2018-03-11 18:18:36,2018-03-11 18:30:37.931962,2018-04-03,2018-04-03 20:36:43.778451,e33c250311160298e5b457ca52720a35,goiania,...,1,550.0,16.0,10.0,16.0,785b20b3b689b670e6b7e30f04eb6fdc,1835b56ce799e6a4dc4eddc053f04066,149,ibitinga,sp
4,195a8be6794c487fe6cfbb97b7c61902,295.989990,47.650002,1,2017-04-20 08:01:08,2017-04-25 08:05:40.405383,2017-05-24,2017-05-04 18:47:45.721758,8a8f7c9a4450f17ba3ee25a5ba821bc7,recife,...,1,3800.0,19.0,27.0,27.0,539155c817eb96914de0b011b4d28d50,8bd0f31cf0a614c658f6763bd02dea69,012,sao_paulo,sp